name: Docker Build

on:
  push:
    branches:
      - develop
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify .dockerignore to uncomment specific lines
        run: |
          sed -i 's/^#proxy_config.json/proxy_config.json/' .dockerignore
          sed -i 's/^#rules_config.json/rules_config.json/' .dockerignore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine Docker Tag
        id: tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAG="stable"
          else
            echo "This workflow is not configured to run for this branch: ${GITHUB_REF_NAME}"
            exit 1
          fi
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/dracan:${{ env.tag }}
