name: Docker Build

on:
  push:
    branches:
    #  - develop    # Run on all pushes to develop
    tags:
    #  - 'v*'       # Run on tagged pushes (e.g., v1.0) on any branch, but will be filtered to main below

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify .dockerignore to uncomment specific lines
        run: |
          sed -i 's/^#proxy_config.json/proxy_config.json/' .dockerignore
          sed -i 's/^#rules_config.json/rules_config.json/' .dockerignore

      - name: Log .dockerignore content (for debugging purposes)
        run: cat .dockerignore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine Docker Tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/develop ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/tags/* && "${GITHUB_REF_NAME}" == "main" ]]; then
            # Extract the tag name for main branch tags
            TAG="${GITHUB_REF#refs/tags/}"
          else
            echo "This workflow is not configured to run for this ref: ${GITHUB_REF}"
            exit 1
          fi
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/dracan:${{ env.tag }}
